"""
Timeframe Aggregation Module
=============================

Canonical chokepoint for deriving higher timeframes from M1 OHLCV data.

Design decisions (from RENKO_KINETRA_DESIGN_SPEC.md §4.3):
  - M1 is the ONLY source timeframe downloaded from brokers.
  - All higher timeframes (M5, M15, M30, H1, H4, D1, W1) are aggregated from M1.
  - Aggregated files are cache, not source — always re-derivable from M1.
  - If M1 is updated (new bars downloaded), aggregated files MUST be regenerated.

Aggregation rules (standard OHLCV):
  open   = first open in window
  high   = max high in window
  low    = min low in window
  close  = last close in window
  volume = sum of tick_volume in window
  spread = median spread in window (representative, not sum)

This module is the canonical home for all timeframe aggregation logic.
Import from here — never duplicate.

Usage::

    from kinetra.aggregation import (
        aggregate_ohlcv,
        aggregate_m1_to_timeframe,
        aggregate_m1_to_all,
        discover_m1_files,
        AggregationResult,
        SUPPORTED_TIMEFRAMES,
    )

See Also:
    - ``docs/MANUAL.md §4.3`` — design specification
    - ``kinetra/broker.py`` — OHLCV normalisation (upstream)
    - ``kinetra/renko/brick_engine.py`` — Renko construction (downstream)
"""

from __future__ import annotations

import logging
import os
import time
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)

# ══════════════════════════════════════════════════════════════════════════════
# Constants
# ══════════════════════════════════════════════════════════════════════════════

#: Supported target timeframes with their duration in minutes.
#: Ordered from finest to coarsest.  M1 is NOT listed because it is the source.
TIMEFRAME_MINUTES: Dict[str, int] = {
    "M5": 5,
    "M15": 15,
    "M30": 30,
    "H1": 60,
    "H4": 240,
    "D1": 1440,
    "W1": 10080,
}

#: All supported target timeframe labels (for iteration / validation).
SUPPORTED_TIMEFRAMES: Tuple[str, ...] = tuple(TIMEFRAME_MINUTES.keys())

#: Default set of timeframes to generate when no explicit list is given.
#: Renko-only architecture: M30 is the sole required aggregation target.
#: DSP (Variance Ratio) and brick construction both operate on M30 closes.
#: Other timeframes (M5, M15, H1, H4) remain SUPPORTED but are no longer
#: generated by default — pass them explicitly if needed for research.
DEFAULT_TIMEFRAMES: Tuple[str, ...] = ("M30",)

#: Pandas offset aliases used for resampling.
_TF_RESAMPLE_RULE: Dict[str, str] = {
    "M5": "5min",
    "M15": "15min",
    "M30": "30min",
    "H1": "1h",
    "H4": "4h",
    "D1": "1D",
    "W1": "1W",
}

#: Minimum M1 bars required to produce a meaningful aggregated file.
#: At M1 resolution, 1440 bars ≈ 1 trading day.
MIN_M1_BARS: int = 1000

#: Canonical OHLCV columns expected in M1 source data (lowercase).
CANONICAL_COLUMNS: Tuple[str, ...] = ("time", "open", "high", "low", "close", "volume")

#: Optional columns that are carried through aggregation when present.
OPTIONAL_COLUMNS: Tuple[str, ...] = ("spread",)

#: M1 data directory (relative to project root).
#: Points to the canonical multi-broker storage root.
#: NOTE: The old "data/master_m1" path was a phantom — all active downloaders
#: (MetaAPI, cTrader, MT5) write to data/master_standardized/.  This constant
#: is kept for any code that references it by name but must resolve correctly.
M1_DATA_DIR: str = "data/master_standardized"

#: Aggregated data directory (relative to project root).
AGGREGATED_DATA_DIR: str = "data/aggregated"


# ══════════════════════════════════════════════════════════════════════════════
# Dataclasses
# ══════════════════════════════════════════════════════════════════════════════


@dataclass(frozen=True, slots=True)
class AggregationResult:
    """Result of aggregating one M1 file to a target timeframe.

    Attributes
    ----------
    symbol : str
        Instrument symbol (e.g. ``"EURUSD"``).
    source_tf : str
        Source timeframe (always ``"M1"``).
    target_tf : str
        Target timeframe (e.g. ``"H1"``).
    source_bars : int
        Number of M1 bars in the source.
    target_bars : int
        Number of bars in the aggregated output.
    compression_ratio : float
        ``source_bars / target_bars`` — how many M1 bars per target bar.
    output_path : Optional[Path]
        Where the aggregated file was written (None if not saved).
    elapsed_seconds : float
        Wall-clock time for the aggregation.
    success : bool
        Whether the aggregation completed without errors.
    error : Optional[str]
        Error message if ``success`` is False.
    """

    symbol: str
    source_tf: str = "M1"
    target_tf: str = ""
    source_bars: int = 0
    target_bars: int = 0
    compression_ratio: float = 0.0
    output_path: Optional[Path] = None
    elapsed_seconds: float = 0.0
    success: bool = True
    error: Optional[str] = None


@dataclass
class BatchAggregationReport:
    """Summary of a batch aggregation run across multiple symbols/timeframes.

    Attributes
    ----------
    results : List[AggregationResult]
        Individual results for each symbol/timeframe pair.
    total_m1_bars : int
        Total M1 bars processed across all symbols.
    total_output_bars : int
        Total aggregated bars produced.
    total_files_written : int
        Number of output files successfully written.
    total_elapsed_seconds : float
        Wall-clock time for the entire batch.
    errors : List[str]
        Error messages from failed aggregations.
    """

    results: List[AggregationResult] = field(default_factory=list)
    total_m1_bars: int = 0
    total_output_bars: int = 0
    total_files_written: int = 0
    total_elapsed_seconds: float = 0.0
    errors: List[str] = field(default_factory=list)

    @property
    def success_count(self) -> int:
        return sum(1 for r in self.results if r.success)

    @property
    def failure_count(self) -> int:
        return sum(1 for r in self.results if not r.success)

    def summary(self) -> str:
        """Human-readable summary of the batch run."""
        lines = [
            f"Aggregation complete: {self.success_count} succeeded, {self.failure_count} failed",
            f"  M1 bars processed:    {self.total_m1_bars:,}",
            f"  Output bars produced: {self.total_output_bars:,}",
            f"  Files written:        {self.total_files_written}",
            f"  Elapsed:              {self.total_elapsed_seconds:.1f}s",
        ]
        if self.errors:
            lines.append(f"  Errors ({len(self.errors)}):")
            for err in self.errors[:10]:
                lines.append(f"    • {err}")
            if len(self.errors) > 10:
                lines.append(f"    … and {len(self.errors) - 10} more")
        return "\n".join(lines)


# ══════════════════════════════════════════════════════════════════════════════
# Core aggregation functions
# ══════════════════════════════════════════════════════════════════════════════


def validate_m1_dataframe(df: pd.DataFrame, symbol: str = "UNKNOWN") -> Tuple[bool, str]:
    """Validate that a DataFrame contains valid M1 OHLCV data.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame to validate.  Must have ``time``, ``open``, ``high``,
        ``low``, ``close``, ``volume`` columns.
    symbol : str
        Symbol name for error messages.

    Returns
    -------
    (valid, message) : Tuple[bool, str]
        ``valid`` is True if the data passes all checks.
        ``message`` describes the first failure found, or "OK".
    """
    if df is None or df.empty:
        return False, f"{symbol}: DataFrame is empty or None"

    # Check required columns — 'time' can be the index (DatetimeIndex) instead
    # of a regular column, which is perfectly valid for aggregation.
    required_price_cols = [c for c in CANONICAL_COLUMNS if c != "time"]
    has_time = (
        "time" in df.columns
        or isinstance(df.index, pd.DatetimeIndex)
        or (hasattr(df.index, "name") and df.index.name == "time")
    )
    missing = [c for c in required_price_cols if c not in df.columns]
    if missing:
        # Try case-insensitive match
        df_cols_lower = {c.lower(): c for c in df.columns}
        still_missing = [c for c in missing if c.lower() not in df_cols_lower]
        if still_missing:
            return False, f"{symbol}: missing columns: {still_missing}"
    if not has_time:
        # Try case-insensitive match for time
        df_cols_lower = {c.lower(): c for c in df.columns}
        if "time" not in df_cols_lower:
            return False, f"{symbol}: missing columns: ['time']"

    if len(df) < MIN_M1_BARS:
        return False, f"{symbol}: only {len(df)} bars (need ≥{MIN_M1_BARS})"

    # Check for NaN in price columns
    price_cols = ["open", "high", "low", "close"]
    available_price_cols = [c for c in price_cols if c in df.columns]
    nan_count = df[available_price_cols].isna().sum().sum()
    if nan_count > 0:
        return False, f"{symbol}: {nan_count} NaN values in price columns"

    # Check for non-positive prices
    for col in available_price_cols:
        if (df[col] <= 0).any():
            return False, f"{symbol}: non-positive values in '{col}'"

    # Check OHLC consistency: high ≥ low
    if "high" in df.columns and "low" in df.columns:
        violations = (df["high"] < df["low"]).sum()
        if violations > 0:
            return False, f"{symbol}: {violations} bars where high < low"

    return True, "OK"


def normalise_m1_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Normalise column names to lowercase canonical form.

    Handles common variations: ``Open``→``open``, ``Time``→``time``,
    ``tickVolume``→``volume``, ``tick_volume``→``volume``.

    Parameters
    ----------
    df : pd.DataFrame
        Raw M1 DataFrame.

    Returns
    -------
    pd.DataFrame
        DataFrame with canonical lowercase column names.
    """
    rename_map = {}
    col_lower = {c.lower(): c for c in df.columns}

    # Standard case normalisation
    for canon in CANONICAL_COLUMNS + OPTIONAL_COLUMNS:
        if canon not in df.columns and canon in col_lower:
            rename_map[col_lower[canon]] = canon
        elif canon not in df.columns:
            # Check common aliases
            aliases = {
                "volume": ["tickvolume", "tick_volume", "vol", "tickvol"],
                "time": ["datetime", "date", "timestamp"],
            }
            for alias in aliases.get(canon, []):
                if alias in col_lower:
                    rename_map[col_lower[alias]] = canon
                    break

    if rename_map:
        df = df.rename(columns=rename_map)

    return df


def aggregate_ohlcv(
    df_m1: pd.DataFrame,
    target_tf: str,
    *,
    validate: bool = True,
    symbol: str = "UNKNOWN",
) -> Optional[pd.DataFrame]:
    """Aggregate M1 OHLCV data to a higher timeframe.

    This is the canonical aggregation function.  All other aggregation
    entry points delegate to this.

    Parameters
    ----------
    df_m1 : pd.DataFrame
        M1 OHLCV data with columns: ``time``, ``open``, ``high``, ``low``,
        ``close``, ``volume``.  Optionally ``spread``.
    target_tf : str
        Target timeframe label: one of ``SUPPORTED_TIMEFRAMES``
        (``"M5"``, ``"M15"``, ``"M30"``, ``"H1"``, ``"H4"``, ``"D1"``, ``"W1"``).
    validate : bool
        If True, validate the input DataFrame before aggregating.
    symbol : str
        Symbol name for logging / error messages.

    Returns
    -------
    pd.DataFrame or None
        Aggregated OHLCV DataFrame with the same column schema as input,
        or None if validation fails or no bars can be produced.

    Raises
    ------
    ValueError
        If ``target_tf`` is not in ``SUPPORTED_TIMEFRAMES``.

    Notes
    -----
    Aggregation rules:

    - ``open``   = first open in each window
    - ``high``   = max high in each window
    - ``low``    = min low in each window
    - ``close``  = last close in each window
    - ``volume`` = sum of volume in each window
    - ``spread`` = median spread in each window (if present)

    The function uses ``pandas.DataFrame.resample()`` with ``label='left'``
    and ``closed='left'`` semantics, matching the MetaAPI / MT5 convention
    where the bar timestamp marks the **start** of the bar's time window.

    Examples
    --------
    >>> import pandas as pd
    >>> from kinetra.aggregation import aggregate_ohlcv
    >>> m1 = pd.read_csv("data/master_standardized/forex/EURUSD/EURUSD_M1_*.csv")
    >>> h1 = aggregate_ohlcv(m1, "H1", symbol="EURUSD")
    >>> print(h1.shape)  # 60× fewer rows than M1
    """
    if target_tf not in TIMEFRAME_MINUTES:
        raise ValueError(
            f"Unsupported target timeframe '{target_tf}'. "
            f"Must be one of: {', '.join(SUPPORTED_TIMEFRAMES)}"
        )

    # Normalise columns
    df = normalise_m1_columns(df_m1.copy())

    # Validate
    if validate:
        valid, msg = validate_m1_dataframe(df, symbol)
        if not valid:
            logger.warning("Validation failed for %s: %s", symbol, msg)
            return None

    # Ensure 'time' is datetime and set as index for resampling
    if "time" in df.columns:
        df["time"] = pd.to_datetime(df["time"], utc=True, errors="coerce")
        df = df.dropna(subset=["time"])
        df = df.set_index("time")
    elif isinstance(df.index, pd.DatetimeIndex):
        if df.index.tz is None:
            df.index = df.index.tz_localize("UTC")
    else:
        logger.warning("%s: no 'time' column and index is not DatetimeIndex", symbol)
        return None

    # Sort ascending (paranoia — MetaAPI sometimes returns descending)
    df = df.sort_index()

    # Remove duplicates
    df = df[~df.index.duplicated(keep="first")]

    # Build aggregation dict
    agg_dict = {
        "open": "first",
        "high": "max",
        "low": "min",
        "close": "last",
        "volume": "sum",
    }

    # Handle optional columns
    has_spread = "spread" in df.columns
    if has_spread:
        agg_dict["spread"] = "median"

    # Only aggregate columns that exist
    agg_dict = {k: v for k, v in agg_dict.items() if k in df.columns}

    if not agg_dict:
        logger.warning("%s: no OHLCV columns found after normalisation", symbol)
        return None

    # Resample
    rule = _TF_RESAMPLE_RULE[target_tf]
    try:
        resampled = df.resample(rule, label="left", closed="left").agg(agg_dict)
    except Exception as exc:
        logger.error("%s → %s: resample failed: %s", symbol, target_tf, exc)
        return None

    # Drop bars where all OHLC are NaN (weekend/holiday gaps produce these)
    price_cols = [c for c in ("open", "high", "low", "close") if c in resampled.columns]
    resampled = resampled.dropna(subset=price_cols, how="all")

    if resampled.empty:
        logger.warning("%s → %s: no bars after aggregation", symbol, target_tf)
        return None

    # Forward-fill any remaining NaN in price columns (partial windows at boundaries)
    for col in price_cols:
        resampled[col] = resampled[col].ffill()

    # Fill volume NaN with 0
    if "volume" in resampled.columns:
        resampled["volume"] = resampled["volume"].fillna(0).astype(np.int64)

    # Fill spread NaN with forward-fill then 0
    if has_spread and "spread" in resampled.columns:
        resampled["spread"] = resampled["spread"].ffill().fillna(0)

    # Reset index to get 'time' back as a column
    resampled = resampled.reset_index()
    resampled = resampled.rename(columns={"index": "time"})

    # Ensure time column name is correct
    if "time" not in resampled.columns and resampled.columns[0] != "time":
        # The reset_index might use the index name
        first_col = resampled.columns[0]
        if pd.api.types.is_datetime64_any_dtype(resampled[first_col]):
            resampled = resampled.rename(columns={first_col: "time"})

    # Validate OHLC consistency in output
    if "high" in resampled.columns and "low" in resampled.columns:
        # Fix any floating-point edge cases
        mask = resampled["high"] < resampled["low"]
        if mask.any():
            resampled.loc[mask, "high"] = resampled.loc[mask, ["high", "low"]].max(axis=1)

    compression = len(df) / max(len(resampled), 1)
    logger.info(
        "%s: M1 (%d bars) → %s (%d bars), compression %.1f:1",
        symbol,
        len(df),
        target_tf,
        len(resampled),
        compression,
    )

    return resampled


# ══════════════════════════════════════════════════════════════════════════════
# File-based aggregation helpers
# ══════════════════════════════════════════════════════════════════════════════


def load_m1_csv(path: Path) -> Optional[pd.DataFrame]:
    """Load an M1 CSV file with automatic format detection.

    Handles both comma-separated and tab-separated files, with or without
    header rows.  Normalises column names to canonical lowercase form.

    Parameters
    ----------
    path : Path
        Path to the M1 CSV file.

    Returns
    -------
    pd.DataFrame or None
        Loaded and normalised DataFrame, or None on failure.
    """
    if not path.exists():
        logger.warning("M1 file not found: %s", path)
        return None

    # Fast path: use PyArrow-accelerated reader for comma-separated CSVs
    # (canonical Kinetra format).  ~20× faster than pd.read_csv on large
    # M1 files (950K rows: ~50 ms vs ~1177 ms).  The time column is parsed
    # natively in C++ — downstream aggregate_ohlcv() handles the already-
    # parsed datetime column gracefully (to_datetime on datetime64 is a no-op).
    from kinetra.csv_reader import read_ohlcv_fast

    try:
        df = read_ohlcv_fast(path, sort=False, deduplicate=False)
        df = normalise_m1_columns(df)
        return df
    except Exception:
        pass

    # Fallback: tab-separated (MT5 export format) — pyarrow doesn't handle
    # tab-separated well, so use pandas C-engine directly.
    try:
        df = pd.read_csv(path, sep="\t")
        df = normalise_m1_columns(df)
        return df
    except Exception as exc:
        logger.error("Failed to read %s: %s", path, exc)
        return None


def _extract_symbol_from_path(path: Path) -> str:
    """Extract the instrument symbol from a file path.

    Expected patterns:
      - ``…/SYMBOL/SYMBOL_M1_*.csv`` → ``SYMBOL``
      - ``…/SYMBOL_M1_*.csv`` → ``SYMBOL``

    Falls back to the parent directory name if the filename pattern
    doesn't match.
    """
    stem = path.stem  # e.g. "EURUSD_M1_202201010000_202312310000"
    parts = stem.split("_")
    if len(parts) >= 2:
        return parts[0]
    # Fallback: use parent directory name
    return path.parent.name


def _extract_dates_from_path(path: Path) -> Tuple[str, str]:
    """Extract start and end date strings from an M1 filename.

    Expected pattern: ``SYMBOL_M1_YYYYMMDDHHNN_YYYYMMDDHHNN.csv``

    Returns
    -------
    (start_str, end_str) : Tuple[str, str]
        Date strings, or empty strings if parsing fails.
    """
    stem = path.stem
    parts = stem.split("_")
    if len(parts) >= 4:
        return parts[2], parts[3]
    return "", ""


def aggregate_m1_file(
    m1_path: Path,
    target_tf: str,
    output_dir: Optional[Path] = None,
    *,
    symbol: Optional[str] = None,
    overwrite: bool = False,
) -> AggregationResult:
    """Aggregate a single M1 CSV file to a target timeframe and save.

    Parameters
    ----------
    m1_path : Path
        Path to the M1 CSV file.
    target_tf : str
        Target timeframe (e.g. ``"H1"``).
    output_dir : Path or None
        Directory to write the output file.  If None, uses the default
        ``data/aggregated/{TF}/{category}/{SYMBOL}/`` layout.
    symbol : str or None
        Override symbol name (auto-detected from path if None).
    overwrite : bool
        If True, overwrite existing output files.  If False, skip
        files that already exist.

    Returns
    -------
    AggregationResult
        Result of the aggregation including output path and statistics.
    """
    t0 = time.monotonic()
    sym = symbol or _extract_symbol_from_path(m1_path)

    # Load
    df = load_m1_csv(m1_path)
    if df is None:
        return AggregationResult(
            symbol=sym,
            target_tf=target_tf,
            success=False,
            error=f"Failed to load M1 file: {m1_path}",
            elapsed_seconds=time.monotonic() - t0,
        )

    source_bars = len(df)

    # Determine output path
    if output_dir is None:
        # Auto-detect category from the M1 path structure
        # Expected: data/master_m1/{category}/{SYMBOL}/SYMBOL_M1_*.csv
        # or legacy: data/master_standardized/{category}/{SYMBOL}/SYMBOL_M1_*.csv
        category = _infer_category_from_path(m1_path)
        project_root = _find_project_root(m1_path)
        output_dir = project_root / AGGREGATED_DATA_DIR / target_tf / category / sym

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Build output filename
    start_str, end_str = _extract_dates_from_path(m1_path)
    if start_str and end_str:
        out_filename = f"{sym}_{target_tf}_{start_str}_{end_str}.csv"
    else:
        # Derive dates from the data itself
        if "time" in df.columns:
            times = pd.to_datetime(df["time"], errors="coerce").dropna()
            if len(times) >= 2:
                start_str = times.iloc[0].strftime("%Y%m%d%H%M")
                end_str = times.iloc[-1].strftime("%Y%m%d%H%M")
                out_filename = f"{sym}_{target_tf}_{start_str}_{end_str}.csv"
            else:
                out_filename = f"{sym}_{target_tf}.csv"
        else:
            out_filename = f"{sym}_{target_tf}.csv"

    out_path = output_dir / out_filename

    # Check if already exists
    if out_path.exists() and not overwrite:
        return AggregationResult(
            symbol=sym,
            target_tf=target_tf,
            source_bars=source_bars,
            target_bars=0,
            output_path=out_path,
            success=True,
            error="skipped (already exists)",
            elapsed_seconds=time.monotonic() - t0,
        )

    # Aggregate
    result_df = aggregate_ohlcv(df, target_tf, symbol=sym)
    if result_df is None:
        return AggregationResult(
            symbol=sym,
            target_tf=target_tf,
            source_bars=source_bars,
            success=False,
            error=f"Aggregation produced no output for {sym} → {target_tf}",
            elapsed_seconds=time.monotonic() - t0,
        )

    target_bars = len(result_df)
    compression = source_bars / max(target_bars, 1)

    # Save atomically (write to temp, then rename)
    try:
        _atomic_write_csv(result_df, out_path)
    except Exception as exc:
        return AggregationResult(
            symbol=sym,
            target_tf=target_tf,
            source_bars=source_bars,
            target_bars=target_bars,
            compression_ratio=compression,
            success=False,
            error=f"Failed to write {out_path}: {exc}",
            elapsed_seconds=time.monotonic() - t0,
        )

    return AggregationResult(
        symbol=sym,
        target_tf=target_tf,
        source_bars=source_bars,
        target_bars=target_bars,
        compression_ratio=compression,
        output_path=out_path,
        success=True,
        elapsed_seconds=time.monotonic() - t0,
    )


def aggregate_m1_to_all(
    m1_path: Path,
    timeframes: Optional[Sequence[str]] = None,
    output_base: Optional[Path] = None,
    *,
    symbol: Optional[str] = None,
    overwrite: bool = False,
) -> List[AggregationResult]:
    """Aggregate a single M1 file to all requested timeframes.

    Parameters
    ----------
    m1_path : Path
        Path to the M1 CSV file.
    timeframes : sequence of str or None
        Target timeframes.  Defaults to ``DEFAULT_TIMEFRAMES``.
    output_base : Path or None
        Base directory for aggregated output.  If None, uses the default
        layout under ``data/aggregated/``.
    symbol : str or None
        Override symbol name.
    overwrite : bool
        If True, overwrite existing files.

    Returns
    -------
    List[AggregationResult]
        One result per target timeframe.
    """
    if timeframes is None:
        timeframes = DEFAULT_TIMEFRAMES

    sym = symbol or _extract_symbol_from_path(m1_path)
    results = []

    for tf in timeframes:
        if tf not in TIMEFRAME_MINUTES:
            results.append(
                AggregationResult(
                    symbol=sym,
                    target_tf=tf,
                    success=False,
                    error=f"Unsupported timeframe: {tf}",
                )
            )
            continue

        if output_base is not None:
            category = _infer_category_from_path(m1_path)
            broker_path = _infer_broker_path_from_path(m1_path)
            if broker_path:
                out_dir = output_base / tf / Path(broker_path) / category / sym
            else:
                out_dir = output_base / tf / category / sym
        else:
            out_dir = None

        result = aggregate_m1_file(
            m1_path,
            tf,
            output_dir=out_dir,
            symbol=sym,
            overwrite=overwrite,
        )
        results.append(result)

    return results


def aggregate_batch(
    m1_dir: Path,
    timeframes: Optional[Sequence[str]] = None,
    output_base: Optional[Path] = None,
    *,
    symbols: Optional[List[str]] = None,
    overwrite: bool = False,
    max_workers: Optional[int] = None,
) -> BatchAggregationReport:
    """Aggregate all M1 files in a directory tree to higher timeframes.

    Parameters
    ----------
    m1_dir : Path
        Root directory containing M1 CSV files (searched recursively).
    timeframes : sequence of str or None
        Target timeframes.  Defaults to ``DEFAULT_TIMEFRAMES``.
    output_base : Path or None
        Base directory for output.
    symbols : list of str or None
        If provided, only process these symbols.  Others are skipped.
    overwrite : bool
        Overwrite existing aggregated files.

    Returns
    -------
    BatchAggregationReport
        Summary of the batch run.
    """
    t0 = time.monotonic()
    report = BatchAggregationReport()

    m1_files = discover_m1_files(m1_dir)
    if not m1_files:
        report.errors.append(f"No M1 files found in {m1_dir}")
        report.total_elapsed_seconds = time.monotonic() - t0
        return report

    logger.info("Found %d M1 files in %s", len(m1_files), m1_dir)

    selected_files: List[Path] = []
    if symbols is None:
        selected_files = m1_files
    else:
        wanted = {s.strip().upper() for s in symbols if s and s.strip()}
        for m1_path in m1_files:
            sym = _extract_symbol_from_path(m1_path).upper()
            iid = _instrument_id_from_path(m1_path).upper()
            if sym in wanted or iid in wanted:
                selected_files.append(m1_path)

    if not selected_files:
        report.errors.append("No matching M1 files after symbol/instrument filter")
        report.total_elapsed_seconds = time.monotonic() - t0
        return report

    workers = max_workers if max_workers is not None else int(os.getenv("KINETRA_AGG_WORKERS", "4"))
    workers = max(1, int(workers))

    def _run_one(path: Path) -> List[AggregationResult]:
        sym = _extract_symbol_from_path(path)
        return aggregate_m1_to_all(
            path,
            timeframes=timeframes,
            output_base=output_base,
            symbol=sym,
            overwrite=overwrite,
        )

    if workers == 1 or len(selected_files) == 1:
        all_results = [_run_one(p) for p in selected_files]
    else:
        with ThreadPoolExecutor(max_workers=workers) as pool:
            all_results = list(pool.map(_run_one, selected_files))

    for results in all_results:
        for r in results:
            report.results.append(r)
            if r.success and r.error != "skipped (already exists)":
                report.total_m1_bars += r.source_bars
                report.total_output_bars += r.target_bars
                report.total_files_written += 1
            elif not r.success:
                report.errors.append(f"{r.symbol} → {r.target_tf}: {r.error}")

    report.total_elapsed_seconds = time.monotonic() - t0
    return report


# ══════════════════════════════════════════════════════════════════════════════
# Discovery helpers
# ══════════════════════════════════════════════════════════════════════════════


def discover_m1_files(
    root_dir: Path,
    *,
    min_size_bytes: int = 1024,
) -> List[Path]:
    """Recursively discover M1 CSV files in a directory tree.

    Matches files named ``*_M1_*.csv`` (case-insensitive) that are at least
    ``min_size_bytes`` in size.

    Parameters
    ----------
    root_dir : Path
        Root directory to search.
    min_size_bytes : int
        Minimum file size to consider.  Tiny files are likely empty or corrupt.

    Returns
    -------
    List[Path]
        Sorted list of M1 file paths.
    """
    root = Path(root_dir)
    if not root.exists():
        return []

    m1_files = []
    for csv_path in root.rglob("*.csv"):
        stem_upper = csv_path.stem.upper()
        if "_M1_" in stem_upper or stem_upper.endswith("_M1"):
            if csv_path.stat().st_size >= min_size_bytes:
                m1_files.append(csv_path)

    return sorted(m1_files)


def discover_m1_symbols(root_dir: Path) -> Dict[str, Path]:
    """Discover M1 files and return a symbol → path mapping.

    When multiple M1 files exist for the same symbol, the largest file
    (most complete data) is selected.

    Parameters
    ----------
    root_dir : Path
        Root directory to search.

    Returns
    -------
    Dict[str, Path]
        Mapping of symbol name to its best M1 file path.
    """
    files = discover_m1_files(root_dir)
    symbols: Dict[str, Path] = {}

    for path in files:
        sym = _extract_symbol_from_path(path)
        if sym not in symbols or path.stat().st_size > symbols[sym].stat().st_size:
            symbols[sym] = path

    return symbols


def discover_m1_instruments(root_dir: Path) -> Dict[str, Path]:
    """Discover M1 files keyed by broker-qualified instrument id.

    Example ids:
      - ``metaapi/vantage_demo_12345/XAUUSD``
      - ``ctrader/pepperstone_live_9988/NAS100``
      - ``EURUSD`` (legacy flat layout)
    """
    files = discover_m1_files(root_dir)
    instruments: Dict[str, Path] = {}
    for path in files:
        iid = _instrument_id_from_path(path)
        if iid not in instruments or path.stat().st_size > instruments[iid].stat().st_size:
            instruments[iid] = path
    return instruments


def check_aggregation_freshness(
    m1_path: Path,
    aggregated_dir: Path,
    target_tf: str,
) -> bool:
    """Check if aggregated data is up-to-date relative to the M1 source.

    Returns True if the aggregated file exists and is newer than the M1 file.
    Returns False if regeneration is needed.

    Parameters
    ----------
    m1_path : Path
        Path to the M1 source file.
    aggregated_dir : Path
        Directory where aggregated files live.
    target_tf : str
        Target timeframe to check.

    Returns
    -------
    bool
        True if the aggregated file is fresh (no regeneration needed).
    """
    sym = _extract_symbol_from_path(m1_path)
    category = _infer_category_from_path(m1_path)
    broker_path = _infer_broker_path_from_path(m1_path)
    pattern = f"{sym}_{target_tf}_*.csv"
    if broker_path:
        search_root = aggregated_dir / target_tf / Path(broker_path) / category / sym
    else:
        search_root = aggregated_dir / target_tf / category / sym
    agg_files = list(search_root.glob(pattern)) if search_root.exists() else []
    if not agg_files and not broker_path:
        # Fallback for ad-hoc output dirs used by tests/one-off scripts.
        agg_files = list(aggregated_dir.rglob(pattern))
    if not agg_files:
        return False

    # Check modification time
    m1_mtime = m1_path.stat().st_mtime
    newest_agg = max(f.stat().st_mtime for f in agg_files)

    return newest_agg > m1_mtime


def find_stale_aggregations(
    m1_dir: Path,
    aggregated_dir: Path,
    timeframes: Optional[Sequence[str]] = None,
) -> List[Tuple[Path, str]]:
    """Find M1 files whose aggregated outputs are stale or missing.

    Parameters
    ----------
    m1_dir : Path
        Root directory with M1 source files.
    aggregated_dir : Path
        Root directory with aggregated files.
    timeframes : sequence of str or None
        Timeframes to check.  Defaults to ``DEFAULT_TIMEFRAMES``.

    Returns
    -------
    List[Tuple[Path, str]]
        List of ``(m1_path, target_tf)`` pairs that need regeneration.
    """
    if timeframes is None:
        timeframes = DEFAULT_TIMEFRAMES

    m1_files = discover_m1_files(m1_dir)
    stale: List[Tuple[Path, str]] = []

    for m1_path in m1_files:
        for tf in timeframes:
            if not check_aggregation_freshness(m1_path, aggregated_dir, tf):
                stale.append((m1_path, tf))

    return stale


# ══════════════════════════════════════════════════════════════════════════════
# Internal helpers
# ══════════════════════════════════════════════════════════════════════════════


def _find_project_root(path: Path) -> Path:
    """Walk up from ``path`` looking for a directory containing ``kinetra/``.

    Falls back to ``path.parent.parent.parent`` if the marker is not found.
    """
    current = path.resolve()
    for _ in range(10):
        if (current / "kinetra").is_dir():
            return current
        parent = current.parent
        if parent == current:
            break
        current = parent

    # Fallback: assume data/master_m1/{cat}/{sym}/file.csv → 4 levels up
    return path.resolve().parent.parent.parent.parent


_KNOWN_CATEGORIES = frozenset(
    ("forex", "crypto", "metals", "energy", "indices", "commodities", "other")
)


def _infer_category_from_path(path: Path) -> str:
    """Infer the asset category from the file path.

    Expected layouts (from shallowest to deepest)::

      ``data/master_m1/{category}/{SYMBOL}/file.csv``
      ``data/master_standardized/{category}/{SYMBOL}/file.csv``
      ``data/master_standardized/{broker}/{category}/{SYMBOL}/file.csv``
      ``data/master_standardized/{broker_type}/{account}/{category}/{SYMBOL}/file.csv``

    The function scans up to 3 levels past the data-directory marker to
    find the first path component that matches a known category name.

    Returns ``"other"`` if the category cannot be inferred.
    """
    parts = path.resolve().parts
    # Look for known data directory markers
    for i, part in enumerate(parts):
        if part in ("master_m1", "master_standardized", "aggregated"):
            # Scan up to 3 components past the marker to find a category.
            # This handles:
            #   marker/{category}/…                (depth 1 — legacy flat)
            #   marker/{broker}/{category}/…        (depth 2 — single-level broker)
            #   marker/{broker_type}/{account}/{category}/…  (depth 3 — §28 multi-broker)
            for offset in range(1, 4):
                idx = i + offset
                if idx < len(parts):
                    candidate = parts[idx].lower()
                    if candidate in _KNOWN_CATEGORIES:
                        return candidate

    return "other"


def _infer_broker_path_from_path(path: Path) -> str:
    """Infer broker/account subpath from an M1 source file path.

    Returns an empty string for legacy flat layouts with no broker namespace.
    """
    parts = path.resolve().parts
    marker_idx = -1
    for i, part in enumerate(parts):
        if part in ("master_standardized", "master_m1"):
            marker_idx = i
            break
    if marker_idx < 0:
        return ""

    category_idx = -1
    for offset in range(1, 6):
        idx = marker_idx + offset
        if idx < len(parts) and parts[idx].lower() in _KNOWN_CATEGORIES:
            category_idx = idx
            break
    if category_idx < 0:
        return ""

    broker_parts = parts[marker_idx + 1 : category_idx]
    return "/".join(p for p in broker_parts if p)


def _instrument_id_from_path(path: Path) -> str:
    """Build broker-qualified instrument id for uniqueness across brokers."""
    symbol = _extract_symbol_from_path(path)
    broker_path = _infer_broker_path_from_path(path)
    return f"{broker_path}/{symbol}" if broker_path else symbol


def _atomic_write_csv(df: pd.DataFrame, path: Path) -> None:
    """Write a DataFrame to CSV atomically (write-to-temp then rename).

    Parameters
    ----------
    df : pd.DataFrame
        Data to write.
    path : Path
        Destination path.
    """
    import shutil
    import tempfile

    path.parent.mkdir(parents=True, exist_ok=True)

    # Write to a temporary file in the same directory (same filesystem for atomic rename)
    fd, tmp_path = tempfile.mkstemp(
        dir=path.parent,
        prefix=f".{path.stem}_",
        suffix=".csv.tmp",
    )
    try:
        df.to_csv(tmp_path, index=False)
        # Atomic rename (same filesystem)
        shutil.move(tmp_path, str(path))
    except Exception:
        # Clean up temp file on failure
        try:
            Path(tmp_path).unlink(missing_ok=True)
        except Exception:
            pass
        raise
    finally:
        try:
            os.close(fd)
        except Exception:
            pass


# ══════════════════════════════════════════════════════════════════════════════
# Migration helper — move legacy multi-TF CSVs, keep only M1
# ══════════════════════════════════════════════════════════════════════════════


def identify_non_m1_files(data_dir: Path) -> Dict[str, List[Path]]:
    """Identify all non-M1 CSV files in master_standardized for cleanup.

    Returns a dictionary keyed by timeframe label (e.g. ``"H1"``, ``"H4"``)
    with lists of file paths that should be removed or archived once M1
    data is available and aggregation is in place.

    Parameters
    ----------
    data_dir : Path
        Root data directory (e.g. ``data/master_standardized/``).

    Returns
    -------
    Dict[str, List[Path]]
        Timeframe → list of file paths.
    """
    non_m1: Dict[str, List[Path]] = {}

    if not data_dir.exists():
        return non_m1

    for csv_path in data_dir.rglob("*.csv"):
        stem_upper = csv_path.stem.upper()
        parts = stem_upper.split("_")
        if len(parts) >= 2:
            tf_label = parts[1]
            if tf_label in ("M5", "M15", "M30", "H1", "H4", "D1", "W1"):
                non_m1.setdefault(tf_label, []).append(csv_path)

    return non_m1


def archive_non_m1_files(
    data_dir: Path,
    archive_dir: Path,
    *,
    dry_run: bool = True,
) -> Dict[str, int]:
    """Move non-M1 CSV files from master_standardized to an archive directory.

    This is a one-time migration helper.  After running, only M1 files
    remain in ``master_standardized/`` and all higher-TF files are
    safely archived (not deleted).

    Parameters
    ----------
    data_dir : Path
        Source directory (e.g. ``data/master_standardized/``).
    archive_dir : Path
        Destination archive directory.
    dry_run : bool
        If True (default), only report what would be moved.

    Returns
    -------
    Dict[str, int]
        Count of files moved (or that would be moved) per timeframe.
    """
    import shutil

    non_m1 = identify_non_m1_files(data_dir)
    counts: Dict[str, int] = {}

    for tf, paths in non_m1.items():
        counts[tf] = len(paths)
        if dry_run:
            logger.info("[DRY RUN] Would archive %d %s files", len(paths), tf)
            continue

        for src in paths:
            # Preserve the relative path structure in the archive
            rel = src.relative_to(data_dir)
            dst = archive_dir / rel
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(src), str(dst))

        logger.info("Archived %d %s files to %s", len(paths), tf, archive_dir)

    return counts
