#!/usr/bin/env python3
"""
MetaAPI Credential Setup
========================

Centralized script to configure MetaAPI credentials for Kinetra.

This script:
1. Prompts for your MetaAPI token (once)
2. Lets you select/add multiple broker accounts
3. Saves everything securely to .env
4. Validates that credentials work

Usage:
    python scripts/setup_metaapi_credentials.py

    # Re-run to add more accounts:
    python scripts/setup_metaapi_credentials.py --add-account

Environment Variables Set:
    METAAPI_TOKEN          - Your MetaAPI API token
    METAAPI_ACCOUNT_ID     - Default account ID
    METAAPI_ACCOUNT_<NAME> - Named accounts (e.g., METAAPI_ACCOUNT_VANTAGE)
"""

import argparse
import asyncio
import getpass
import os
import sys
from pathlib import Path
from typing import Dict, List, Optional

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))


def print_header(title: str):
    """Print formatted section header."""
    print("\n" + "=" * 80)
    print(f" {title}")
    print("=" * 80)


def read_env_file() -> Dict[str, str]:
    """
    Read existing .env file.

    Returns:
        Dictionary of key=value pairs
    """
    env_file = project_root / ".env"
    env_vars = {}

    if env_file.exists():
        with open(env_file, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, value = line.split("=", 1)
                    env_vars[key.strip()] = value.strip().strip('"').strip("'")

    return env_vars


def write_env_file(env_vars: Dict[str, str], comments: Optional[Dict[str, str]] = None):
    """
    Write .env file with variables and optional comments.

    Args:
        env_vars: Dictionary of key=value pairs
        comments: Optional dictionary of key=comment pairs
    """
    env_file = project_root / ".env"
    comments = comments or {}

    with open(env_file, "w") as f:
        f.write("# Kinetra MetaAPI Configuration\n")
        f.write("# Generated by scripts/setup_metaapi_credentials.py\n")
        f.write("# DO NOT COMMIT THIS FILE - IT CONTAINS SECRETS\n\n")

        # Write token first
        if "METAAPI_TOKEN" in env_vars:
            if "METAAPI_TOKEN" in comments:
                f.write(f"# {comments['METAAPI_TOKEN']}\n")
            f.write(f"METAAPI_TOKEN={env_vars['METAAPI_TOKEN']}\n\n")

        # Write default account
        if "METAAPI_ACCOUNT_ID" in env_vars:
            f.write("# Default MetaAPI Account\n")
            f.write(f"METAAPI_ACCOUNT_ID={env_vars['METAAPI_ACCOUNT_ID']}\n\n")

        # Write named accounts
        account_keys = [
            k
            for k in env_vars.keys()
            if k.startswith("METAAPI_ACCOUNT_") and k != "METAAPI_ACCOUNT_ID"
        ]
        if account_keys:
            f.write("# Named Broker Accounts\n")
            for key in sorted(account_keys):
                if key in comments:
                    f.write(f"# {comments[key]}\n")
                f.write(f"{key}={env_vars[key]}\n")
            f.write("\n")

        # Write other variables
        other_keys = [
            k
            for k in env_vars.keys()
            if k not in ["METAAPI_TOKEN", "METAAPI_ACCOUNT_ID"]
            and not k.startswith("METAAPI_ACCOUNT_")
        ]
        if other_keys:
            f.write("# Other Configuration\n")
            for key in sorted(other_keys):
                if key in comments:
                    f.write(f"# {comments[key]}\n")
                f.write(f"{key}={env_vars[key]}\n")

    print(f"✅ Configuration saved to {env_file}")


def get_token_from_user() -> Optional[str]:
    """
    Prompt user for MetaAPI token.

    Returns:
        Token string or None if cancelled
    """
    print("\n📋 Get your MetaAPI token from: https://app.metaapi.cloud/token")
    print("   (The token is a long JWT string starting with 'eyJ...')")
    print()

    try:
        token = getpass.getpass("Enter your MetaAPI token (input hidden): ").strip()
        if not token:
            print("❌ No token entered")
            return None

        if not token.startswith("eyJ"):
            print("⚠️  Warning: Token doesn't look like a JWT (should start with 'eyJ')")
            confirm = input("Continue anyway? (y/N): ").strip().lower()
            if confirm != "y":
                return None

        return token

    except KeyboardInterrupt:
        print("\n❌ Cancelled")
        return None


async def validate_token(token: str) -> bool:
    """
    Validate that the MetaAPI token works.

    Args:
        token: MetaAPI token to validate

    Returns:
        True if valid, False otherwise
    """
    try:
        from metaapi_cloud_sdk import MetaApi

        print("\n🔄 Validating token...")
        api = MetaApi(token)

        # Try to fetch accounts to validate token
        accounts = await api.metatrader_account_api.get_accounts_with_infinite_scroll_pagination()

        print(f"✅ Token is valid! Found {len(accounts)} account(s)")
        return True

    except ImportError:
        print("⚠️  metaapi-cloud-sdk not installed - skipping validation")
        print("   Install with: pip install metaapi-cloud-sdk")
        return True  # Assume valid if package not installed

    except Exception as e:
        print(f"❌ Token validation failed: {e}")
        return False


async def list_and_select_accounts(token: str) -> List[Dict[str, str]]:
    """
    List MetaAPI accounts and let user select/label them.

    Args:
        token: MetaAPI token

    Returns:
        List of account dictionaries with id, name, label
    """
    try:
        from metaapi_cloud_sdk import MetaApi

        print("\n🔄 Fetching your MetaAPI accounts...")
        api = MetaApi(token)
        accounts = await api.metatrader_account_api.get_accounts_with_infinite_scroll_pagination()

        if not accounts:
            print("❌ No accounts found in your MetaAPI account")
            print("   Add an account at: https://app.metaapi.cloud/accounts")
            return []

        print(f"\n✅ Found {len(accounts)} account(s):\n")

        # Display accounts
        account_list = []
        for i, acc in enumerate(accounts, 1):
            account_info = {
                "id": acc.id,
                "name": acc.name,
                "login": acc.login,
                "server": acc.server,
                "type": getattr(acc, "type", "N/A"),
                "state": getattr(acc, "state", "N/A"),
            }
            account_list.append(account_info)

            print(f"  [{i}] {acc.name}")
            print(f"      Login: {acc.login} | Server: {acc.server}")
            print(f"      ID: {acc.id}")
            print(f"      State: {account_info['state']}\n")

        return account_list

    except ImportError:
        print("❌ metaapi-cloud-sdk not installed")
        print("   Install with: pip install metaapi-cloud-sdk")
        return []

    except Exception as e:
        print(f"❌ Failed to fetch accounts: {e}")
        return []


def select_accounts_interactively(account_list: List[Dict[str, str]]) -> List[Dict[str, str]]:
    """
    Let user select which accounts to configure.

    Args:
        account_list: List of available accounts

    Returns:
        List of selected accounts with labels
    """
    if not account_list:
        return []

    print("\n📝 Select accounts to configure:")
    print("   Enter account numbers separated by commas (e.g., 1,3)")
    print("   Or press Enter to configure all accounts")
    print()

    try:
        selection = input("Account numbers: ").strip()

        if not selection:
            # Configure all
            selected = account_list
        else:
            # Parse selection
            indices = [int(x.strip()) - 1 for x in selection.split(",")]
            selected = [account_list[i] for i in indices if 0 <= i < len(account_list)]

        if not selected:
            print("❌ No accounts selected")
            return []

        # Get labels for each account
        labeled_accounts = []
        for acc in selected:
            print(f"\n📋 Configure account: {acc['name']} (ID: {acc['id']})")
            print("   Enter a short label for this account (e.g., 'VANTAGE', 'DEMO', 'LIVE')")
            print("   Or press Enter to use the account name")

            label = input("   Label: ").strip().upper()
            if not label:
                # Use sanitized account name
                label = acc["name"].upper().replace(" ", "_").replace("-", "_")

            # Remove special characters
            label = "".join(c for c in label if c.isalnum() or c == "_")

            acc["label"] = label
            labeled_accounts.append(acc)

        return labeled_accounts

    except (ValueError, IndexError):
        print("❌ Invalid selection")
        return []
    except KeyboardInterrupt:
        print("\n❌ Cancelled")
        return []


async def setup_credentials(add_account_only: bool = False):
    """
    Main credential setup flow.

    Args:
        add_account_only: If True, only add accounts (don't prompt for token)
    """
    print_header("MetaAPI Credential Setup")

    # Read existing .env
    env_vars = read_env_file()
    comments = {}

    # Step 1: Handle token
    if add_account_only and "METAAPI_TOKEN" in env_vars:
        print("✅ Using existing METAAPI_TOKEN from .env")
        token = env_vars["METAAPI_TOKEN"]
    else:
        if "METAAPI_TOKEN" in env_vars:
            print(f"✅ Found existing METAAPI_TOKEN in .env")
            use_existing = input("Use existing token? (Y/n): ").strip().lower()
            if use_existing != "n":
                token = env_vars["METAAPI_TOKEN"]
            else:
                token = get_token_from_user()
        else:
            token = get_token_from_user()

        if not token:
            print("\n❌ Setup cancelled - no token provided")
            return

        # Validate token
        if not await validate_token(token):
            print("\n❌ Token validation failed - setup cancelled")
            return

        env_vars["METAAPI_TOKEN"] = token
        comments["METAAPI_TOKEN"] = "MetaAPI API Token (from https://app.metaapi.cloud/token)"

    # Step 2: List and select accounts
    account_list = await list_and_select_accounts(token)

    if not account_list:
        print("\n⚠️  No accounts available to configure")
        # Still save the token
        write_env_file(env_vars, comments)
        return

    # Step 3: Let user select and label accounts
    selected_accounts = select_accounts_interactively(account_list)

    if not selected_accounts:
        print("\n⚠️  No accounts selected")
        # Still save the token
        write_env_file(env_vars, comments)
        return

    # Step 4: Set default account and save
    print_header("Configuration Summary")

    # Set first account as default
    env_vars["METAAPI_ACCOUNT_ID"] = selected_accounts[0]["id"]
    print(f"✅ Default account: {selected_accounts[0]['name']}")
    print(f"   ID: {selected_accounts[0]['id']}")

    # Save labeled accounts
    for acc in selected_accounts:
        var_name = f"METAAPI_ACCOUNT_{acc['label']}"
        env_vars[var_name] = acc["id"]
        comments[var_name] = f"{acc['name']} (Login: {acc['login']}, Server: {acc['server']})"
        print(f"✅ {var_name} = {acc['id']}")
        print(f"   {acc['name']} (Login: {acc['login']})")

    # Write .env file
    print()
    write_env_file(env_vars, comments)

    print_header("Setup Complete!")
    print("✅ Credentials configured successfully")
    print()
    print("Environment variables set:")
    print(f"  • METAAPI_TOKEN (hidden)")
    print(f"  • METAAPI_ACCOUNT_ID = {env_vars['METAAPI_ACCOUNT_ID']}")
    for acc in selected_accounts:
        print(f"  • METAAPI_ACCOUNT_{acc['label']} = {env_vars[f'METAAPI_ACCOUNT_{acc['label']}']}")
    print()
    print("Next steps:")
    print("  1. Download data: python scripts/download/download_interactive.py")
    print("  2. Run tests: python scripts/run_exhaustive_tests.py --generate-dashboard")
    print()
    print("To add more accounts later, run:")
    print("  python scripts/setup_metaapi_credentials.py --add-account")


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(description="Setup MetaAPI credentials for Kinetra")
    parser.add_argument(
        "--add-account",
        action="store_true",
        help="Add additional accounts without re-entering token",
    )

    args = parser.parse_args()

    # Check for metaapi package
    try:
        import metaapi_cloud_sdk
    except ImportError:
        print("❌ ERROR: metaapi-cloud-sdk package not installed")
        print("   Install with: pip install metaapi-cloud-sdk")
        print("   Or: pip install -e '.[dev]'")
        sys.exit(1)

    # Run setup
    asyncio.run(setup_credentials(add_account_only=args.add_account))


if __name__ == "__main__":
    main()
